# Generated by Django 4.2 on 2023-04-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=25, null=True)),
                ('total_calls', models.IntegerField(blank=True, default=0, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
