# Generated by Django 4.2 on 2023-04-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='Date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
